// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodeUI_QuanLyKhachSan
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethodThanhToan - Use 'RecordedMethodThanhToanParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodThanhToan()
        {
            #region Variable Declarations
            WinComboBox uIItem5262022ComboBox = this.UIQUẢNLÍKHÁCHSẠNWindow.UIThanhtoánWindow.UITableLayoutPanel3Window.UIItem5262022ComboBox;
            WinComboBox uIItem5262022ComboBox1 = this.UIQUẢNLÍKHÁCHSẠNWindow.UIThanhtoánWindow.UITableLayoutPanel3Window.UIItem5262022ComboBox1;
            WinButton uITìmkiếmButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UIThanhtoánWindow.UITableLayoutPanel7Window.UITìmkiếmButton;
            #endregion

            // Type '{Enter}{Tab}' in '5/26/2022' combo box
            Keyboard.SendKeys(uIItem5262022ComboBox, this.RecordedMethodThanhToanParams.UIItem5262022ComboBoxSendKeys, ModifierKeys.None);

            // Type '{Enter}{Tab}' in '5/26/2022' combo box
            Keyboard.SendKeys(uIItem5262022ComboBox1, this.RecordedMethodThanhToanParams.UIItem5262022ComboBox1SendKeys, ModifierKeys.None);

            // Type '{Enter}{Tab}' in 'Tìm kiếm' button
            Keyboard.SendKeys(uITìmkiếmButton, this.RecordedMethodThanhToanParams.UITìmkiếmButtonSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Test Dang Nhap
        /// </summary>
        public void RecordedMethodDangNhap()
        {
            #region Variable Declarations
            WinEdit uITxtUserNameEdit = this.UIFrmDangNhapWindow.UITxtUserNameWindow.UITxtUserNameEdit;
            WinEdit uITxtPassEdit = this.UIFrmDangNhapWindow.UITxtPassWindow.UITxtPassEdit;
            WinWindow uIĐăngnhậpWindow = this.UIFrmDangNhapWindow.UIFrmDangNhapClient.UIĐăngnhậpWindow;
            #endregion

            // Type '0703051386' in 'txtUserName' text box
            uITxtUserNameEdit.Text = this.RecordedMethodDangNhapParams.UITxtUserNameEditText;

            // Type '********' in 'txtPass' text box
            Keyboard.SendKeys(uITxtPassEdit, this.RecordedMethodDangNhapParams.UITxtPassEditSendKeys, true);

            // Click 'Đăng nhập' window
            Mouse.Click(uIĐăngnhậpWindow, new Point(164, 173));
        }
        
        /// <summary>
        /// RecordedMethodDangNhap1 - Use 'RecordedMethodDangNhap1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodDangNhap1()
        {
            #region Variable Declarations
            WinEdit uITxtUserNameEdit = this.UIFrmDangNhapWindow.UITxtUserNameWindow.UITxtUserNameEdit;
            WinWindow uITxtPassWindow = this.UIFrmDangNhapWindow.UIFrmDangNhapClient.UITxtPassWindow;
            WinWindow uIPictureBox3Window = this.UIFrmDangNhapWindow.UIFrmDangNhapClient.UIPictureBox3Window;
            WinEdit uITxtPassEdit = this.UIFrmDangNhapWindow.UITxtPassWindow.UITxtPassEdit;
            WinButton uIĐăngnhậpButton = this.UIFrmDangNhapWindow.UIĐăngnhậpWindow.UIĐăngnhậpButton;
            #endregion

            // Type '0703051386' in 'txtUserName' text box
            uITxtUserNameEdit.Text = this.RecordedMethodDangNhap1Params.UITxtUserNameEditText;

            // Move 'txtPass' window to 'pictureBox3' window
            //uIPictureBox3Window.EnsureClickable(new Point(114, 134));
            //Mouse.StartDragging(uITxtPassWindow, new Point(115, 139));
            //Mouse.StopDragging(uIPictureBox3Window, new Point(114, 134));

            // Type '********' in 'txtPass' text box
            Keyboard.SendKeys(uITxtPassEdit, this.RecordedMethodDangNhap1Params.UITxtPassEditSendKeys, true);

            // Type '{Enter}' in 'Đăng nhập' button
            Keyboard.SendKeys(uIĐăngnhậpButton, this.RecordedMethodDangNhap1Params.UIĐăngnhậpButtonSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// RecordedMethodThemChucVu - Use 'RecordedMethodThemChucVuParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodThemChucVu()
        {
            #region Variable Declarations
            WinPane uIQuảnlínhânviênPane = this.UIQUẢNLÍKHÁCHSẠNWindow.UILowerRibbonPane.UIQuảnlínhânviênPane;
            WinEdit uIItemEdit = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQuảnlíthôngtinnhânviWindow.UITxt_tenChucVuEdit.UIItemEdit;
            WinButton uIThêmButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQuảnlíthôngtinnhânviWindow.UITableLayoutPanel3Window.UIThêmButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Quản lí nhân viên' pane
            Mouse.Click(uIQuảnlínhânviênPane, new Point(114, 91));

            // Type 'Bao ve' in text box
            uIItemEdit.Text = this.RecordedMethodThemChucVuParams.UIItemEditText;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethodThemChucVuParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Thêm' button
            Keyboard.SendKeys(uIThêmButton, this.RecordedMethodThemChucVuParams.UIThêmButtonSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'OK' button
            Keyboard.SendKeys(uIOKButton, this.RecordedMethodThemChucVuParams.UIOKButtonSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// RecordedMethodThemPhong - Use 'RecordedMethodThemPhongParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodThemPhong()
        {
            #region Variable Declarations
            WinWindow uIRibbonWindow = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQUẢNLÍKHÁCHSẠNClient.UIRibbonWindow;
            WinWindow uIPhòngĐôiWindow = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_tenLoaiEdit.UIPhòngĐôiWindow;
            WinEdit uIItemEdit = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_tenLoaiEdit.UIItemEdit;
            WinEdit uIItemEdit1 = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_soGiuongEdit.UIItemEdit;
            WinButton uIThêmButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITableLayoutPanel3Window.UIThêmButton;
            WinButton uISửaButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITableLayoutPanel3Window.UISửaButton;
            WinButton uIXoáButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITableLayoutPanel3Window.UIXoáButton;
            WinEdit uIItemEdit2 = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_GiaGioEdit.UIItemEdit;
            WinEdit uIItemEdit3 = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_GiaNgayEdit.UIItemEdit;
            WinEdit uIItemEdit4 = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITxt_GiaThangEdit.UIItemEdit;
            WinWindow uIThêmWindow = this.UIQUẢNLÍKHÁCHSẠNWindow.UICHỈNHSỬATHÔNGTINPHÒNWindow.UITableLayoutPanel3Window.UIThêmWindow;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'ribbon' window
            Mouse.Click(uIRibbonWindow, new Point(241, 187));

            // Click 'Phòng Đôi' window
            Mouse.Click(uIPhòngĐôiWindow, new Point(319, 126));

            // Type 'Phòng Ba' in text box
            uIItemEdit.Text = this.RecordedMethodThemPhongParams.UIItemEditText;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethodThemPhongParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type '3' in text box
            uIItemEdit1.Text = this.RecordedMethodThemPhongParams.UIItemEditText1;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit1, this.RecordedMethodThemPhongParams.UIItemEditSendKeys1, ModifierKeys.None);

            // Type '{Tab}' in 'Thêm' button
            Keyboard.SendKeys(uIThêmButton, this.RecordedMethodThemPhongParams.UIThêmButtonSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'Sửa' button
            Keyboard.SendKeys(uISửaButton, this.RecordedMethodThemPhongParams.UISửaButtonSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'Xoá' button
            Keyboard.SendKeys(uIXoáButton, this.RecordedMethodThemPhongParams.UIXoáButtonSendKeys, ModifierKeys.None);

            // Type '70000' in text box
            uIItemEdit2.Text = this.RecordedMethodThemPhongParams.UIItemEditText2;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit2, this.RecordedMethodThemPhongParams.UIItemEditSendKeys2, ModifierKeys.None);

            // Type '700000' in text box
            uIItemEdit3.Text = this.RecordedMethodThemPhongParams.UIItemEditText3;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit3, this.RecordedMethodThemPhongParams.UIItemEditSendKeys3, ModifierKeys.None);

            // Type '7000000' in text box
            uIItemEdit4.Text = this.RecordedMethodThemPhongParams.UIItemEditText4;

            // Click 'Thêm' window
            Mouse.Click(uIThêmWindow, new Point(169, 218));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(70, 13));
        }
        
        /// <summary>
        /// RecordedMethodThemChucVu1 - Use 'RecordedMethodThemChucVu1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodThemChucVu1()
        {
            #region Variable Declarations
            //WinWindow uIBaoveWindow = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQuảnlíthôngtinnhânviWindow.UITxt_tenChucVuEdit.UIBaoveWindow;
            WinEdit uIItemEdit = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQuảnlíthôngtinnhânviWindow.UITxt_tenChucVuEdit.UIItemEdit;
            WinButton uIThêmButton = this.UIQUẢNLÍKHÁCHSẠNWindow.UIQuảnlíthôngtinnhânviWindow.UITableLayoutPanel3Window.UIThêmButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Bao ve' window
            //Mouse.Click(uIBaoveWindow, new Point(160, 122));

            // Type 'Nhan vien thu ngan' in text box
            uIItemEdit.Text = this.RecordedMethodThemChucVu1Params.UIItemEditText;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethodThemChucVu1Params.UIItemEditSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Thêm' button
            Keyboard.SendKeys(uIThêmButton, this.RecordedMethodThemChucVu1Params.UIThêmButtonSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'OK' button
            Keyboard.SendKeys(uIOKButton, this.RecordedMethodThemChucVu1Params.UIOKButtonSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethodThanhToanParams RecordedMethodThanhToanParams
        {
            get
            {
                if ((this.mRecordedMethodThanhToanParams == null))
                {
                    this.mRecordedMethodThanhToanParams = new RecordedMethodThanhToanParams();
                }
                return this.mRecordedMethodThanhToanParams;
            }
        }
        
        public virtual RecordedMethodDangNhapParams RecordedMethodDangNhapParams
        {
            get
            {
                if ((this.mRecordedMethodDangNhapParams == null))
                {
                    this.mRecordedMethodDangNhapParams = new RecordedMethodDangNhapParams();
                }
                return this.mRecordedMethodDangNhapParams;
            }
        }
        
        public virtual RecordedMethodDangNhap1Params RecordedMethodDangNhap1Params
        {
            get
            {
                if ((this.mRecordedMethodDangNhap1Params == null))
                {
                    this.mRecordedMethodDangNhap1Params = new RecordedMethodDangNhap1Params();
                }
                return this.mRecordedMethodDangNhap1Params;
            }
        }
        
        public virtual RecordedMethodThemChucVuParams RecordedMethodThemChucVuParams
        {
            get
            {
                if ((this.mRecordedMethodThemChucVuParams == null))
                {
                    this.mRecordedMethodThemChucVuParams = new RecordedMethodThemChucVuParams();
                }
                return this.mRecordedMethodThemChucVuParams;
            }
        }
        
        public virtual RecordedMethodThemPhongParams RecordedMethodThemPhongParams
        {
            get
            {
                if ((this.mRecordedMethodThemPhongParams == null))
                {
                    this.mRecordedMethodThemPhongParams = new RecordedMethodThemPhongParams();
                }
                return this.mRecordedMethodThemPhongParams;
            }
        }
        
        public virtual RecordedMethodThemChucVu1Params RecordedMethodThemChucVu1Params
        {
            get
            {
                if ((this.mRecordedMethodThemChucVu1Params == null))
                {
                    this.mRecordedMethodThemChucVu1Params = new RecordedMethodThemChucVu1Params();
                }
                return this.mRecordedMethodThemChucVu1Params;
            }
        }
        
        public UIQUẢNLÍKHÁCHSẠNWindow UIQUẢNLÍKHÁCHSẠNWindow
        {
            get
            {
                if ((this.mUIQUẢNLÍKHÁCHSẠNWindow == null))
                {
                    this.mUIQUẢNLÍKHÁCHSẠNWindow = new UIQUẢNLÍKHÁCHSẠNWindow();
                }
                return this.mUIQUẢNLÍKHÁCHSẠNWindow;
            }
        }
        
        public UIFrmDangNhapWindow UIFrmDangNhapWindow
        {
            get
            {
                if ((this.mUIFrmDangNhapWindow == null))
                {
                    this.mUIFrmDangNhapWindow = new UIFrmDangNhapWindow();
                }
                return this.mUIFrmDangNhapWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethodThanhToanParams mRecordedMethodThanhToanParams;
        
        private RecordedMethodDangNhapParams mRecordedMethodDangNhapParams;
        
        private RecordedMethodDangNhap1Params mRecordedMethodDangNhap1Params;
        
        private RecordedMethodThemChucVuParams mRecordedMethodThemChucVuParams;
        
        private RecordedMethodThemPhongParams mRecordedMethodThemPhongParams;
        
        private RecordedMethodThemChucVu1Params mRecordedMethodThemChucVu1Params;
        
        private UIQUẢNLÍKHÁCHSẠNWindow mUIQUẢNLÍKHÁCHSẠNWindow;
        
        private UIFrmDangNhapWindow mUIFrmDangNhapWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodThanhToan'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodThanhToanParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Enter}{Tab}' in '5/26/2022' combo box
        /// </summary>
        public string UIItem5262022ComboBoxSendKeys = "{Enter}{Tab}";
        
        /// <summary>
        /// Type '{Enter}{Tab}' in '5/26/2022' combo box
        /// </summary>
        public string UIItem5262022ComboBox1SendKeys = "{Enter}{Tab}";
        
        /// <summary>
        /// Type '{Enter}{Tab}' in 'Tìm kiếm' button
        /// </summary>
        public string UITìmkiếmButtonSendKeys = "{Enter}{Tab}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodDangNhap'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodDangNhapParams
    {
        
        #region Fields
        /// <summary>
        /// Type '0703051386' in 'txtUserName' text box
        /// </summary>
        public string UITxtUserNameEditText = "0703051386";
        
        /// <summary>
        /// Type '********' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditSendKeys = "2Oxm3dAuzpTO5Npam0fkew==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodDangNhap1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodDangNhap1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '0703051386' in 'txtUserName' text box
        /// </summary>
        public string UITxtUserNameEditText = "0703051386";
        
        /// <summary>
        /// Type '********' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditSendKeys = "LhN8aH3/sMZ8FDsaa2gg68CE0hC30afa";
        
        /// <summary>
        /// Type '{Enter}' in 'Đăng nhập' button
        /// </summary>
        public string UIĐăngnhậpButtonSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodThemChucVu'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodThemChucVuParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Bao ve' in text box
        /// </summary>
        public string UIItemEditText = "Bao ve";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Thêm' button
        /// </summary>
        public string UIThêmButtonSendKeys = "{Enter}";
        
        /// <summary>
        /// Type '{Enter}' in 'OK' button
        /// </summary>
        public string UIOKButtonSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodThemPhong'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodThemPhongParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Phòng Ba' in text box
        /// </summary>
        public string UIItemEditText = "Phòng Ba";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '3' in text box
        /// </summary>
        public string UIItemEditText1 = "3";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'Thêm' button
        /// </summary>
        public string UIThêmButtonSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'Sửa' button
        /// </summary>
        public string UISửaButtonSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'Xoá' button
        /// </summary>
        public string UIXoáButtonSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '70000' in text box
        /// </summary>
        public string UIItemEditText2 = "70000";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys2 = "{Tab}";
        
        /// <summary>
        /// Type '700000' in text box
        /// </summary>
        public string UIItemEditText3 = "700000";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys3 = "{Tab}";
        
        /// <summary>
        /// Type '7000000' in text box
        /// </summary>
        public string UIItemEditText4 = "7000000";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodThemChucVu1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethodThemChucVu1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Nhan vien thu ngan' in text box
        /// </summary>
        public string UIItemEditText = "Nhan vien thu ngan";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Thêm' button
        /// </summary>
        public string UIThêmButtonSendKeys = "{Enter}";
        
        /// <summary>
        /// Type '{Enter}' in 'OK' button
        /// </summary>
        public string UIOKButtonSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIQUẢNLÍKHÁCHSẠNWindow : WinWindow
    {
        
        public UIQUẢNLÍKHÁCHSẠNWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "QUẢN LÍ KHÁCH SẠN";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public UIThanhtoánWindow UIThanhtoánWindow
        {
            get
            {
                if ((this.mUIThanhtoánWindow == null))
                {
                    this.mUIThanhtoánWindow = new UIThanhtoánWindow(this);
                }
                return this.mUIThanhtoánWindow;
            }
        }
        
        public UILowerRibbonPane UILowerRibbonPane
        {
            get
            {
                if ((this.mUILowerRibbonPane == null))
                {
                    this.mUILowerRibbonPane = new UILowerRibbonPane(this);
                }
                return this.mUILowerRibbonPane;
            }
        }
        
        public UIQuảnlíthôngtinnhânviWindow UIQuảnlíthôngtinnhânviWindow
        {
            get
            {
                if ((this.mUIQuảnlíthôngtinnhânviWindow == null))
                {
                    this.mUIQuảnlíthôngtinnhânviWindow = new UIQuảnlíthôngtinnhânviWindow(this);
                }
                return this.mUIQuảnlíthôngtinnhânviWindow;
            }
        }
        
        public UIQUẢNLÍKHÁCHSẠNClient UIQUẢNLÍKHÁCHSẠNClient
        {
            get
            {
                if ((this.mUIQUẢNLÍKHÁCHSẠNClient == null))
                {
                    this.mUIQUẢNLÍKHÁCHSẠNClient = new UIQUẢNLÍKHÁCHSẠNClient(this);
                }
                return this.mUIQUẢNLÍKHÁCHSẠNClient;
            }
        }
        
        public UICHỈNHSỬATHÔNGTINPHÒNWindow UICHỈNHSỬATHÔNGTINPHÒNWindow
        {
            get
            {
                if ((this.mUICHỈNHSỬATHÔNGTINPHÒNWindow == null))
                {
                    this.mUICHỈNHSỬATHÔNGTINPHÒNWindow = new UICHỈNHSỬATHÔNGTINPHÒNWindow(this);
                }
                return this.mUICHỈNHSỬATHÔNGTINPHÒNWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIThanhtoánWindow mUIThanhtoánWindow;
        
        private UILowerRibbonPane mUILowerRibbonPane;
        
        private UIQuảnlíthôngtinnhânviWindow mUIQuảnlíthôngtinnhânviWindow;
        
        private UIQUẢNLÍKHÁCHSẠNClient mUIQUẢNLÍKHÁCHSẠNClient;
        
        private UICHỈNHSỬATHÔNGTINPHÒNWindow mUICHỈNHSỬATHÔNGTINPHÒNWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIThanhtoánWindow : WinWindow
    {
        
        public UIThanhtoánWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Thanh toán";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public UITableLayoutPanel3Window UITableLayoutPanel3Window
        {
            get
            {
                if ((this.mUITableLayoutPanel3Window == null))
                {
                    this.mUITableLayoutPanel3Window = new UITableLayoutPanel3Window(this);
                }
                return this.mUITableLayoutPanel3Window;
            }
        }
        
        public UITableLayoutPanel7Window UITableLayoutPanel7Window
        {
            get
            {
                if ((this.mUITableLayoutPanel7Window == null))
                {
                    this.mUITableLayoutPanel7Window = new UITableLayoutPanel7Window(this);
                }
                return this.mUITableLayoutPanel7Window;
            }
        }
        #endregion
        
        #region Fields
        private UITableLayoutPanel3Window mUITableLayoutPanel3Window;
        
        private UITableLayoutPanel7Window mUITableLayoutPanel7Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITableLayoutPanel3Window : WinWindow
    {
        
        public UITableLayoutPanel3Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel3";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItem5262022ComboBox
        {
            get
            {
                if ((this.mUIItem5262022ComboBox == null))
                {
                    this.mUIItem5262022ComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItem5262022ComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "5/26/2022";
                    this.mUIItem5262022ComboBox.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItem5262022ComboBox;
            }
        }
        
        public WinComboBox UIItem5262022ComboBox1
        {
            get
            {
                if ((this.mUIItem5262022ComboBox1 == null))
                {
                    this.mUIItem5262022ComboBox1 = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItem5262022ComboBox1.SearchProperties[WinComboBox.PropertyNames.Name] = "5/26/2022";
                    this.mUIItem5262022ComboBox1.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItem5262022ComboBox1;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItem5262022ComboBox;
        
        private WinComboBox mUIItem5262022ComboBox1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITableLayoutPanel7Window : WinWindow
    {
        
        public UITableLayoutPanel7Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel7";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinButton UITìmkiếmButton
        {
            get
            {
                if ((this.mUITìmkiếmButton == null))
                {
                    this.mUITìmkiếmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITìmkiếmButton.SearchProperties[WinButton.PropertyNames.Name] = "Tìm kiếm";
                    this.mUITìmkiếmButton.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUITìmkiếmButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITìmkiếmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILowerRibbonPane : WinPane
    {
        
        public UILowerRibbonPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Lower Ribbon";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinPane UIQuảnlínhânviênPane
        {
            get
            {
                if ((this.mUIQuảnlínhânviênPane == null))
                {
                    this.mUIQuảnlínhânviênPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIQuảnlínhânviênPane.SearchProperties[WinControl.PropertyNames.Name] = "Quản lí nhân viên";
                    this.mUIQuảnlínhânviênPane.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIQuảnlínhânviênPane;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIQuảnlínhânviênPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIQuảnlíthôngtinnhânviWindow : WinWindow
    {
        
        public UIQuảnlíthôngtinnhânviWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Quản lí thông tin nhân viên";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public UITxt_tenChucVuEdit UITxt_tenChucVuEdit
        {
            get
            {
                if ((this.mUITxt_tenChucVuEdit == null))
                {
                    this.mUITxt_tenChucVuEdit = new UITxt_tenChucVuEdit(this);
                }
                return this.mUITxt_tenChucVuEdit;
            }
        }
        
        public UITableLayoutPanel3Window1 UITableLayoutPanel3Window
        {
            get
            {
                if ((this.mUITableLayoutPanel3Window == null))
                {
                    this.mUITableLayoutPanel3Window = new UITableLayoutPanel3Window1(this);
                }
                return this.mUITableLayoutPanel3Window;
            }
        }
        #endregion
        
        #region Fields
        private UITxt_tenChucVuEdit mUITxt_tenChucVuEdit;
        
        private UITableLayoutPanel3Window1 mUITableLayoutPanel3Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_tenChucVuEdit : WinEdit
    {
        
        public UITxt_tenChucVuEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WinWindow UIBaoveWindow
        {
            get
            {
                if ((this.mUIBaoveWindow == null))
                {
                    this.mUIBaoveWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBaoveWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Bao ve";
                    this.mUIBaoveWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIBaoveWindow.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIBaoveWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        
        private WinWindow mUIBaoveWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITableLayoutPanel3Window1 : WinWindow
    {
        
        public UITableLayoutPanel3Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel3";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinButton UIThêmButton
        {
            get
            {
                if ((this.mUIThêmButton == null))
                {
                    this.mUIThêmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIThêmButton.SearchProperties[WinButton.PropertyNames.Name] = "Thêm";
                    this.mUIThêmButton.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIThêmButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIThêmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIQUẢNLÍKHÁCHSẠNClient : WinClient
    {
        
        public UIQUẢNLÍKHÁCHSẠNClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "QUẢN LÍ KHÁCH SẠN";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinWindow UIRibbonWindow
        {
            get
            {
                if ((this.mUIRibbonWindow == null))
                {
                    this.mUIRibbonWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIRibbonWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "The Ribbon";
                    this.mUIRibbonWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIRibbonWindow.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIRibbonWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIRibbonWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICHỈNHSỬATHÔNGTINPHÒNWindow : WinWindow
    {
        
        public UICHỈNHSỬATHÔNGTINPHÒNWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Chỉnh sửa thông tin phòng";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public UITxt_tenLoaiEdit UITxt_tenLoaiEdit
        {
            get
            {
                if ((this.mUITxt_tenLoaiEdit == null))
                {
                    this.mUITxt_tenLoaiEdit = new UITxt_tenLoaiEdit(this);
                }
                return this.mUITxt_tenLoaiEdit;
            }
        }
        
        public UITxt_soGiuongEdit UITxt_soGiuongEdit
        {
            get
            {
                if ((this.mUITxt_soGiuongEdit == null))
                {
                    this.mUITxt_soGiuongEdit = new UITxt_soGiuongEdit(this);
                }
                return this.mUITxt_soGiuongEdit;
            }
        }
        
        public UITableLayoutPanel3Window2 UITableLayoutPanel3Window
        {
            get
            {
                if ((this.mUITableLayoutPanel3Window == null))
                {
                    this.mUITableLayoutPanel3Window = new UITableLayoutPanel3Window2(this);
                }
                return this.mUITableLayoutPanel3Window;
            }
        }
        
        public UITxt_GiaGioEdit UITxt_GiaGioEdit
        {
            get
            {
                if ((this.mUITxt_GiaGioEdit == null))
                {
                    this.mUITxt_GiaGioEdit = new UITxt_GiaGioEdit(this);
                }
                return this.mUITxt_GiaGioEdit;
            }
        }
        
        public UITxt_GiaNgayEdit UITxt_GiaNgayEdit
        {
            get
            {
                if ((this.mUITxt_GiaNgayEdit == null))
                {
                    this.mUITxt_GiaNgayEdit = new UITxt_GiaNgayEdit(this);
                }
                return this.mUITxt_GiaNgayEdit;
            }
        }
        
        public UITxt_GiaThangEdit UITxt_GiaThangEdit
        {
            get
            {
                if ((this.mUITxt_GiaThangEdit == null))
                {
                    this.mUITxt_GiaThangEdit = new UITxt_GiaThangEdit(this);
                }
                return this.mUITxt_GiaThangEdit;
            }
        }
        #endregion
        
        #region Fields
        private UITxt_tenLoaiEdit mUITxt_tenLoaiEdit;
        
        private UITxt_soGiuongEdit mUITxt_soGiuongEdit;
        
        private UITableLayoutPanel3Window2 mUITableLayoutPanel3Window;
        
        private UITxt_GiaGioEdit mUITxt_GiaGioEdit;
        
        private UITxt_GiaNgayEdit mUITxt_GiaNgayEdit;
        
        private UITxt_GiaThangEdit mUITxt_GiaThangEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_tenLoaiEdit : WinEdit
    {
        
        public UITxt_tenLoaiEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinWindow UIPhòngĐôiWindow
        {
            get
            {
                if ((this.mUIPhòngĐôiWindow == null))
                {
                    this.mUIPhòngĐôiWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPhòngĐôiWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Phòng Đôi";
                    this.mUIPhòngĐôiWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIPhòngĐôiWindow.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIPhòngĐôiWindow;
            }
        }
        
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIPhòngĐôiWindow;
        
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_soGiuongEdit : WinEdit
    {
        
        public UITxt_soGiuongEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITableLayoutPanel3Window2 : WinWindow
    {
        
        public UITableLayoutPanel3Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel3";
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinButton UIThêmButton
        {
            get
            {
                if ((this.mUIThêmButton == null))
                {
                    this.mUIThêmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIThêmButton.SearchProperties[WinButton.PropertyNames.Name] = "Thêm";
                    this.mUIThêmButton.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIThêmButton;
            }
        }
        
        public WinButton UISửaButton
        {
            get
            {
                if ((this.mUISửaButton == null))
                {
                    this.mUISửaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISửaButton.SearchProperties[WinButton.PropertyNames.Name] = "Sửa";
                    this.mUISửaButton.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUISửaButton;
            }
        }
        
        public WinButton UIXoáButton
        {
            get
            {
                if ((this.mUIXoáButton == null))
                {
                    this.mUIXoáButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIXoáButton.SearchProperties[WinButton.PropertyNames.Name] = "Xoá";
                    this.mUIXoáButton.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIXoáButton;
            }
        }
        
        public WinWindow UIThêmWindow
        {
            get
            {
                if ((this.mUIThêmWindow == null))
                {
                    this.mUIThêmWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIThêmWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Thêm";
                    this.mUIThêmWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIThêmWindow.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIThêmWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIThêmButton;
        
        private WinButton mUISửaButton;
        
        private WinButton mUIXoáButton;
        
        private WinWindow mUIThêmWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_GiaGioEdit : WinEdit
    {
        
        public UITxt_GiaGioEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_GiaNgayEdit : WinEdit
    {
        
        public UITxt_GiaNgayEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxt_GiaThangEdit : WinEdit
    {
        
        public UITxt_GiaThangEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItemEdit.WindowTitles.Add("QUẢN LÍ KHÁCH SẠN");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrmDangNhapWindow : WinWindow
    {
        
        public UIFrmDangNhapWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmDangNhap";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public UIFrmDangNhapClient UIFrmDangNhapClient
        {
            get
            {
                if ((this.mUIFrmDangNhapClient == null))
                {
                    this.mUIFrmDangNhapClient = new UIFrmDangNhapClient(this);
                }
                return this.mUIFrmDangNhapClient;
            }
        }
        
        public UITxtUserNameWindow UITxtUserNameWindow
        {
            get
            {
                if ((this.mUITxtUserNameWindow == null))
                {
                    this.mUITxtUserNameWindow = new UITxtUserNameWindow(this);
                }
                return this.mUITxtUserNameWindow;
            }
        }
        
        public UITxtPassWindow UITxtPassWindow
        {
            get
            {
                if ((this.mUITxtPassWindow == null))
                {
                    this.mUITxtPassWindow = new UITxtPassWindow(this);
                }
                return this.mUITxtPassWindow;
            }
        }
        
        public UIĐăngnhậpWindow UIĐăngnhậpWindow
        {
            get
            {
                if ((this.mUIĐăngnhậpWindow == null))
                {
                    this.mUIĐăngnhậpWindow = new UIĐăngnhậpWindow(this);
                }
                return this.mUIĐăngnhậpWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmDangNhapClient mUIFrmDangNhapClient;
        
        private UITxtUserNameWindow mUITxtUserNameWindow;
        
        private UITxtPassWindow mUITxtPassWindow;
        
        private UIĐăngnhậpWindow mUIĐăngnhậpWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrmDangNhapClient : WinClient
    {
        
        public UIFrmDangNhapClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "FrmDangNhap";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtUserNameWindow
        {
            get
            {
                if ((this.mUITxtUserNameWindow == null))
                {
                    this.mUITxtUserNameWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtUserNameWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtUserNameWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUITxtUserNameWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtUserNameWindow;
            }
        }
        
        public WinWindow UIĐăngnhậpWindow
        {
            get
            {
                if ((this.mUIĐăngnhậpWindow == null))
                {
                    this.mUIĐăngnhậpWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIĐăngnhậpWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Đăng nhập";
                    this.mUIĐăngnhậpWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIĐăngnhậpWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUIĐăngnhậpWindow;
            }
        }
        
        public WinWindow UITxtPassWindow
        {
            get
            {
                if ((this.mUITxtPassWindow == null))
                {
                    this.mUITxtPassWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtPassWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtPassWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtPassWindow;
            }
        }
        
        public WinWindow UIPictureBox3Window
        {
            get
            {
                if ((this.mUIPictureBox3Window == null))
                {
                    this.mUIPictureBox3Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPictureBox3Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIPictureBox3Window.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
                    this.mUIPictureBox3Window.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUIPictureBox3Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtUserNameWindow;
        
        private WinWindow mUIĐăngnhậpWindow;
        
        private WinWindow mUITxtPassWindow;
        
        private WinWindow mUIPictureBox3Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtUserNameWindow : WinWindow
    {
        
        public UITxtUserNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtUserName";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtUserNameEdit
        {
            get
            {
                if ((this.mUITxtUserNameEdit == null))
                {
                    this.mUITxtUserNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtUserNameEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtUserNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtUserNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtPassWindow : WinWindow
    {
        
        public UITxtPassWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPass";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPassEdit
        {
            get
            {
                if ((this.mUITxtPassEdit == null))
                {
                    this.mUITxtPassEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPassEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtPassEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPassEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIĐăngnhậpWindow : WinWindow
    {
        
        public UIĐăngnhậpWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnEntry";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinButton UIĐăngnhậpButton
        {
            get
            {
                if ((this.mUIĐăngnhậpButton == null))
                {
                    this.mUIĐăngnhậpButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIĐăngnhậpButton.SearchProperties[WinButton.PropertyNames.Name] = "Đăng nhập";
                    this.mUIĐăngnhậpButton.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUIĐăngnhậpButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIĐăngnhậpButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
