#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_BLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_KhachSan")]
	public partial class DataQLKhachSanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_HinhThuc(tbl_HinhThuc instance);
    partial void Updatetbl_HinhThuc(tbl_HinhThuc instance);
    partial void Deletetbl_HinhThuc(tbl_HinhThuc instance);
    partial void Inserttbl_Phong(tbl_Phong instance);
    partial void Updatetbl_Phong(tbl_Phong instance);
    partial void Deletetbl_Phong(tbl_Phong instance);
    partial void Inserttbl_HoaDon(tbl_HoaDon instance);
    partial void Updatetbl_HoaDon(tbl_HoaDon instance);
    partial void Deletetbl_HoaDon(tbl_HoaDon instance);
    partial void Inserttbl_KhachHang(tbl_KhachHang instance);
    partial void Updatetbl_KhachHang(tbl_KhachHang instance);
    partial void Deletetbl_KhachHang(tbl_KhachHang instance);
    partial void Inserttbl_LoaiNhanVien(tbl_LoaiNhanVien instance);
    partial void Updatetbl_LoaiNhanVien(tbl_LoaiNhanVien instance);
    partial void Deletetbl_LoaiNhanVien(tbl_LoaiNhanVien instance);
    partial void Inserttbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Updatetbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Deletetbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Inserttbl_NhanVien(tbl_NhanVien instance);
    partial void Updatetbl_NhanVien(tbl_NhanVien instance);
    partial void Deletetbl_NhanVien(tbl_NhanVien instance);
    partial void Inserttbl_PhieuThue(tbl_PhieuThue instance);
    partial void Updatetbl_PhieuThue(tbl_PhieuThue instance);
    partial void Deletetbl_PhieuThue(tbl_PhieuThue instance);
    #endregion
		
		public DataQLKhachSanDataContext() : 
				base(global::DAO_BLL.Properties.Settings.Default.QL_KhachSanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLKhachSanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLKhachSanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLKhachSanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLKhachSanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_HinhThuc> tbl_HinhThucs
		{
			get
			{
				return this.GetTable<tbl_HinhThuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Phong> tbl_Phongs
		{
			get
			{
				return this.GetTable<tbl_Phong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this.GetTable<tbl_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhachHang> tbl_KhachHangs
		{
			get
			{
				return this.GetTable<tbl_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LoaiNhanVien> tbl_LoaiNhanViens
		{
			get
			{
				return this.GetTable<tbl_LoaiNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LoaiPhong> tbl_LoaiPhongs
		{
			get
			{
				return this.GetTable<tbl_LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this.GetTable<tbl_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PhieuThue> tbl_PhieuThues
		{
			get
			{
				return this.GetTable<tbl_PhieuThue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HinhThuc")]
	public partial class tbl_HinhThuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhThuc;
		
		private string _TenHinhThuc;
		
		private EntitySet<tbl_PhieuThue> _tbl_PhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhThucChanging(int value);
    partial void OnMaHinhThucChanged();
    partial void OnTenHinhThucChanging(string value);
    partial void OnTenHinhThucChanged();
    #endregion
		
		public tbl_HinhThuc()
		{
			this._tbl_PhieuThues = new EntitySet<tbl_PhieuThue>(new Action<tbl_PhieuThue>(this.attach_tbl_PhieuThues), new Action<tbl_PhieuThue>(this.detach_tbl_PhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					this.OnMaHinhThucChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThuc = value;
					this.SendPropertyChanged("MaHinhThuc");
					this.OnMaHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinhThuc", DbType="NVarChar(50)")]
		public string TenHinhThuc
		{
			get
			{
				return this._TenHinhThuc;
			}
			set
			{
				if ((this._TenHinhThuc != value))
				{
					this.OnTenHinhThucChanging(value);
					this.SendPropertyChanging();
					this._TenHinhThuc = value;
					this.SendPropertyChanged("TenHinhThuc");
					this.OnTenHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HinhThuc_tbl_PhieuThue", Storage="_tbl_PhieuThues", ThisKey="MaHinhThuc", OtherKey="MaHinhThuc")]
		public EntitySet<tbl_PhieuThue> tbl_PhieuThues
		{
			get
			{
				return this._tbl_PhieuThues;
			}
			set
			{
				this._tbl_PhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HinhThuc = this;
		}
		
		private void detach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HinhThuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Phong")]
	public partial class tbl_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private string _TenPhong;
		
		private int _MaLoaiPhong;
		
		private string _TinhTrang;
		
		private EntitySet<tbl_PhieuThue> _tbl_PhieuThues;
		
		private EntityRef<tbl_LoaiPhong> _tbl_LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public tbl_Phong()
		{
			this._tbl_PhieuThues = new EntitySet<tbl_PhieuThue>(new Action<tbl_PhieuThue>(this.attach_tbl_PhieuThues), new Action<tbl_PhieuThue>(this.detach_tbl_PhieuThues));
			this._tbl_LoaiPhong = default(EntityRef<tbl_LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(20)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", DbType="Int NOT NULL")]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					if (this._tbl_LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(20)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_PhieuThue", Storage="_tbl_PhieuThues", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<tbl_PhieuThue> tbl_PhieuThues
		{
			get
			{
				return this._tbl_PhieuThues;
			}
			set
			{
				this._tbl_PhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiPhong_tbl_Phong", Storage="_tbl_LoaiPhong", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong", IsForeignKey=true)]
		public tbl_LoaiPhong tbl_LoaiPhong
		{
			get
			{
				return this._tbl_LoaiPhong.Entity;
			}
			set
			{
				tbl_LoaiPhong previousValue = this._tbl_LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LoaiPhong.Entity = null;
						previousValue.tbl_Phongs.Remove(this);
					}
					this._tbl_LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.tbl_Phongs.Add(this);
						this._MaLoaiPhong = value.MaLoaiPhong;
					}
					else
					{
						this._MaLoaiPhong = default(int);
					}
					this.SendPropertyChanged("tbl_LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = this;
		}
		
		private void detach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HoaDon")]
	public partial class tbl_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private int _MaPhieuThue;
		
		private System.Nullable<System.DateTime> _GioVao;
		
		private System.Nullable<System.DateTime> _GioRa;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<tbl_PhieuThue> _tbl_PhieuThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaPhieuThueChanging(int value);
    partial void OnMaPhieuThueChanged();
    partial void OnGioVaoChanging(System.Nullable<System.DateTime> value);
    partial void OnGioVaoChanged();
    partial void OnGioRaChanging(System.Nullable<System.DateTime> value);
    partial void OnGioRaChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public tbl_HoaDon()
		{
			this._tbl_PhieuThue = default(EntityRef<tbl_PhieuThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThue", DbType="Int NOT NULL")]
		public int MaPhieuThue
		{
			get
			{
				return this._MaPhieuThue;
			}
			set
			{
				if ((this._MaPhieuThue != value))
				{
					if (this._tbl_PhieuThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThue = value;
					this.SendPropertyChanged("MaPhieuThue");
					this.OnMaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioVao", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioVao
		{
			get
			{
				return this._GioVao;
			}
			set
			{
				if ((this._GioVao != value))
				{
					this.OnGioVaoChanging(value);
					this.SendPropertyChanging();
					this._GioVao = value;
					this.SendPropertyChanged("GioVao");
					this.OnGioVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioRa", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioRa
		{
			get
			{
				return this._GioRa;
			}
			set
			{
				if ((this._GioRa != value))
				{
					this.OnGioRaChanging(value);
					this.SendPropertyChanging();
					this._GioRa = value;
					this.SendPropertyChanged("GioRa");
					this.OnGioRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuThue_tbl_HoaDon", Storage="_tbl_PhieuThue", ThisKey="MaPhieuThue", OtherKey="MaPhieuThue", IsForeignKey=true)]
		public tbl_PhieuThue tbl_PhieuThue
		{
			get
			{
				return this._tbl_PhieuThue.Entity;
			}
			set
			{
				tbl_PhieuThue previousValue = this._tbl_PhieuThue.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PhieuThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PhieuThue.Entity = null;
						previousValue.tbl_HoaDons.Remove(this);
					}
					this._tbl_PhieuThue.Entity = value;
					if ((value != null))
					{
						value.tbl_HoaDons.Add(this);
						this._MaPhieuThue = value.MaPhieuThue;
					}
					else
					{
						this._MaPhieuThue = default(int);
					}
					this.SendPropertyChanged("tbl_PhieuThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhachHang")]
	public partial class tbl_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _SDT;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private EntitySet<tbl_PhieuThue> _tbl_PhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public tbl_KhachHang()
		{
			this._tbl_PhieuThues = new EntitySet<tbl_PhieuThue>(new Action<tbl_PhieuThue>(this.attach_tbl_PhieuThues), new Action<tbl_PhieuThue>(this.detach_tbl_PhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_PhieuThue", Storage="_tbl_PhieuThues", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tbl_PhieuThue> tbl_PhieuThues
		{
			get
			{
				return this._tbl_PhieuThues;
			}
			set
			{
				this._tbl_PhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = this;
		}
		
		private void detach_tbl_PhieuThues(tbl_PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LoaiNhanVien")]
	public partial class tbl_LoaiNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiNV;
		
		private string _TenLoai;
		
		private EntitySet<tbl_NhanVien> _tbl_NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiNVChanging(int value);
    partial void OnMaLoaiNVChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tbl_LoaiNhanVien()
		{
			this._tbl_NhanViens = new EntitySet<tbl_NhanVien>(new Action<tbl_NhanVien>(this.attach_tbl_NhanViens), new Action<tbl_NhanVien>(this.detach_tbl_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiNV
		{
			get
			{
				return this._MaLoaiNV;
			}
			set
			{
				if ((this._MaLoaiNV != value))
				{
					this.OnMaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNV = value;
					this.SendPropertyChanged("MaLoaiNV");
					this.OnMaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiNhanVien_tbl_NhanVien", Storage="_tbl_NhanViens", ThisKey="MaLoaiNV", OtherKey="MaLoaiNV")]
		public EntitySet<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this._tbl_NhanViens;
			}
			set
			{
				this._tbl_NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_NhanViens(tbl_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiNhanVien = this;
		}
		
		private void detach_tbl_NhanViens(tbl_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LoaiPhong")]
	public partial class tbl_LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiPhong;
		
		private string _TenLoai;
		
		private System.Nullable<int> _SoGiuong;
		
		private System.Nullable<int> _GiaGio;
		
		private System.Nullable<int> _GiaNgay;
		
		private System.Nullable<int> _GiaThang;
		
		private EntitySet<tbl_Phong> _tbl_Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnSoGiuongChanging(System.Nullable<int> value);
    partial void OnSoGiuongChanged();
    partial void OnGiaGioChanging(System.Nullable<int> value);
    partial void OnGiaGioChanged();
    partial void OnGiaNgayChanging(System.Nullable<int> value);
    partial void OnGiaNgayChanged();
    partial void OnGiaThangChanging(System.Nullable<int> value);
    partial void OnGiaThangChanged();
    #endregion
		
		public tbl_LoaiPhong()
		{
			this._tbl_Phongs = new EntitySet<tbl_Phong>(new Action<tbl_Phong>(this.attach_tbl_Phongs), new Action<tbl_Phong>(this.detach_tbl_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiuong", DbType="Int")]
		public System.Nullable<int> SoGiuong
		{
			get
			{
				return this._SoGiuong;
			}
			set
			{
				if ((this._SoGiuong != value))
				{
					this.OnSoGiuongChanging(value);
					this.SendPropertyChanging();
					this._SoGiuong = value;
					this.SendPropertyChanged("SoGiuong");
					this.OnSoGiuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaGio", DbType="Int")]
		public System.Nullable<int> GiaGio
		{
			get
			{
				return this._GiaGio;
			}
			set
			{
				if ((this._GiaGio != value))
				{
					this.OnGiaGioChanging(value);
					this.SendPropertyChanging();
					this._GiaGio = value;
					this.SendPropertyChanged("GiaGio");
					this.OnGiaGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNgay", DbType="Int")]
		public System.Nullable<int> GiaNgay
		{
			get
			{
				return this._GiaNgay;
			}
			set
			{
				if ((this._GiaNgay != value))
				{
					this.OnGiaNgayChanging(value);
					this.SendPropertyChanging();
					this._GiaNgay = value;
					this.SendPropertyChanged("GiaNgay");
					this.OnGiaNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThang", DbType="Int")]
		public System.Nullable<int> GiaThang
		{
			get
			{
				return this._GiaThang;
			}
			set
			{
				if ((this._GiaThang != value))
				{
					this.OnGiaThangChanging(value);
					this.SendPropertyChanging();
					this._GiaThang = value;
					this.SendPropertyChanged("GiaThang");
					this.OnGiaThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiPhong_tbl_Phong", Storage="_tbl_Phongs", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong")]
		public EntitySet<tbl_Phong> tbl_Phongs
		{
			get
			{
				return this._tbl_Phongs;
			}
			set
			{
				this._tbl_Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Phongs(tbl_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiPhong = this;
		}
		
		private void detach_tbl_Phongs(tbl_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhanVien")]
	public partial class tbl_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _MatKhau;
		
		private int _MaLoaiNV;
		
		private string _GioiTinh;
		
		private string _Diachi;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntityRef<tbl_LoaiNhanVien> _tbl_LoaiNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaLoaiNVChanging(int value);
    partial void OnMaLoaiNVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public tbl_NhanVien()
		{
			this._tbl_LoaiNhanVien = default(EntityRef<tbl_LoaiNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(10)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNV", DbType="Int NOT NULL")]
		public int MaLoaiNV
		{
			get
			{
				return this._MaLoaiNV;
			}
			set
			{
				if ((this._MaLoaiNV != value))
				{
					if (this._tbl_LoaiNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNV = value;
					this.SendPropertyChanged("MaLoaiNV");
					this.OnMaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiNhanVien_tbl_NhanVien", Storage="_tbl_LoaiNhanVien", ThisKey="MaLoaiNV", OtherKey="MaLoaiNV", IsForeignKey=true)]
		public tbl_LoaiNhanVien tbl_LoaiNhanVien
		{
			get
			{
				return this._tbl_LoaiNhanVien.Entity;
			}
			set
			{
				tbl_LoaiNhanVien previousValue = this._tbl_LoaiNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LoaiNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LoaiNhanVien.Entity = null;
						previousValue.tbl_NhanViens.Remove(this);
					}
					this._tbl_LoaiNhanVien.Entity = value;
					if ((value != null))
					{
						value.tbl_NhanViens.Add(this);
						this._MaLoaiNV = value.MaLoaiNV;
					}
					else
					{
						this._MaLoaiNV = default(int);
					}
					this.SendPropertyChanged("tbl_LoaiNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhieuThue")]
	public partial class tbl_PhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuThue;
		
		private int _MaPhong;
		
		private int _MaHinhThuc;
		
		private System.Nullable<System.DateTime> _GioVao;
		
		private System.Nullable<bool> _TinhTrang;
		
		private string _MaKH;
		
		private EntitySet<tbl_HoaDon> _tbl_HoaDons;
		
		private EntityRef<tbl_HinhThuc> _tbl_HinhThuc;
		
		private EntityRef<tbl_KhachHang> _tbl_KhachHang;
		
		private EntityRef<tbl_Phong> _tbl_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuThueChanging(int value);
    partial void OnMaPhieuThueChanged();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnMaHinhThucChanging(int value);
    partial void OnMaHinhThucChanged();
    partial void OnGioVaoChanging(System.Nullable<System.DateTime> value);
    partial void OnGioVaoChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public tbl_PhieuThue()
		{
			this._tbl_HoaDons = new EntitySet<tbl_HoaDon>(new Action<tbl_HoaDon>(this.attach_tbl_HoaDons), new Action<tbl_HoaDon>(this.detach_tbl_HoaDons));
			this._tbl_HinhThuc = default(EntityRef<tbl_HinhThuc>);
			this._tbl_KhachHang = default(EntityRef<tbl_KhachHang>);
			this._tbl_Phong = default(EntityRef<tbl_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThue", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhieuThue
		{
			get
			{
				return this._MaPhieuThue;
			}
			set
			{
				if ((this._MaPhieuThue != value))
				{
					this.OnMaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThue = value;
					this.SendPropertyChanged("MaPhieuThue");
					this.OnMaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Int NOT NULL")]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._tbl_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", DbType="Int NOT NULL")]
		public int MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					if (this._tbl_HinhThuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHinhThucChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThuc = value;
					this.SendPropertyChanged("MaHinhThuc");
					this.OnMaHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioVao", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioVao
		{
			get
			{
				return this._GioVao;
			}
			set
			{
				if ((this._GioVao != value))
				{
					this.OnGioVaoChanging(value);
					this.SendPropertyChanging();
					this._GioVao = value;
					this.SendPropertyChanged("GioVao");
					this.OnGioVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tbl_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuThue_tbl_HoaDon", Storage="_tbl_HoaDons", ThisKey="MaPhieuThue", OtherKey="MaPhieuThue")]
		public EntitySet<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this._tbl_HoaDons;
			}
			set
			{
				this._tbl_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HinhThuc_tbl_PhieuThue", Storage="_tbl_HinhThuc", ThisKey="MaHinhThuc", OtherKey="MaHinhThuc", IsForeignKey=true)]
		public tbl_HinhThuc tbl_HinhThuc
		{
			get
			{
				return this._tbl_HinhThuc.Entity;
			}
			set
			{
				tbl_HinhThuc previousValue = this._tbl_HinhThuc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HinhThuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HinhThuc.Entity = null;
						previousValue.tbl_PhieuThues.Remove(this);
					}
					this._tbl_HinhThuc.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuThues.Add(this);
						this._MaHinhThuc = value.MaHinhThuc;
					}
					else
					{
						this._MaHinhThuc = default(int);
					}
					this.SendPropertyChanged("tbl_HinhThuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_PhieuThue", Storage="_tbl_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tbl_KhachHang tbl_KhachHang
		{
			get
			{
				return this._tbl_KhachHang.Entity;
			}
			set
			{
				tbl_KhachHang previousValue = this._tbl_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_KhachHang.Entity = null;
						previousValue.tbl_PhieuThues.Remove(this);
					}
					this._tbl_KhachHang.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuThues.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tbl_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_PhieuThue", Storage="_tbl_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public tbl_Phong tbl_Phong
		{
			get
			{
				return this._tbl_Phong.Entity;
			}
			set
			{
				tbl_Phong previousValue = this._tbl_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Phong.Entity = null;
						previousValue.tbl_PhieuThues.Remove(this);
					}
					this._tbl_Phong.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuThues.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(int);
					}
					this.SendPropertyChanged("tbl_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuThue = this;
		}
		
		private void detach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuThue = null;
		}
	}
}
#pragma warning restore 1591
